### PR TITLE
Create your first Pyth app part 1 link changed

### PR DESCRIPTION
**Pull request by panditdhamdhere**
At [Page](https://docs.pyth.network/price-feeds/create-your-first-pyth-app/evm/part-2) This tutorial is continuation of the [Part 1: Create a Contract](https://docs.pyth.network/price-feeds/create-your-first-pyth-app/evm/part1). If you haven't completed that part yet, please do so before continuing.  

The actual link is missing Thats why its showing **404 ERROR** -- Thats corrected
image

### CODE REVIEW

**Comment by aditya520** [comment]
Thank you for fixing it. 👍

**Comment by panditdhamdhere** [comment]
Thanks for approving it

**Comment by aditya520** [comment]
Hi @panditdhamdhere Can you rebase with the main?

**Comment by panditdhamdhere** [comment]
cant this pr be merged?

**Pull request merged**
