### PR TITLE
(feat) Cookbook Onboard Integration (AI Assistant)

### PR DESCRIPTION
**Pull request by ClockRide**
The AI assistant and co-pilot is trained on all existing Pyth resources (source code, docs website, etc.) and is available as a standalone modal or as an embeddable button on any page (recommended for technical docs). It answers developer questions about using Pyth, acting as both an enhanced technical documentation search tool and a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev, in addition to Pyth-specific data sources. This allows it to provide the best blockchain developer-focused answers available. Cookbook will assist in tuning and calibrating the AI assistant to ensure the highest quality of responses.

## Preview
https://pyth-docs-cookbookdev.vercel.app/home

image

### CODE REVIEW

**Comment by ClockRide** [comment]
@aditya520, could you please review this when you have a chance?

**Review by aditya520 — APPROVED** [review]

**Review by aditya520 — APPROVED** [review]
Can you run pre-commit

**Comment by ClockRide** [comment]
> Can you run pre-commit

Should be all good now!

**Comment by ClockRide** [comment]
@aditya520 I see that it failed again. Figured that I had to run `pre-commit run --all-files` and not just `pre-commit` to reproduce. Will post back in a moment

**Comment by ClockRide** [comment]
@aditya520 Everything should be good now—sorry for the back and forth. Just a heads up: I adjusted the import to use `@cookbookdev/docsbot/react` instead of `@cookbookdev/docsbot/react-fixed`, which was used before. The former is a lazy-loaded version of our package from `https://www.jsdelivr.com/`, which is preferred over `react-fixed` to avoid increasing your bundle size.

**Pull request merged**
